<a href="https://colab.research.google.com/github/Rathachai/DA-LAB/blob/gh-pages/code/CH_09/CH_09_DA_BOOK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analytics Book : CODE

**ISBN** : 978-616-338-169-9

**Author** : Rathachai Chawuthai

**Year** : 2022

**Copyright** © by KMITL

**Link** : https://github.com/Rathachai/DA-LAB



---

## **Chapter 9 : Recommender System**


---

In [1]:
import numpy as np

In [2]:
# Rating Matrix (-1 means no rating)

R = np.array([
    [ 2, -1, -1,  2,  2],
    [-1,  4,  4, -1,  3],
    [ 1,  4,  1,  2,  2],
    [-1,  2, -1, -1,  5],
    [-1,  2,  1, -1,  5]])

In [3]:
# Set the shape of data

num_users, num_items = R.shape
num_features = 2

In [5]:
# Mean

m = R[R>-1].mean()

In [6]:
# Randomly initial variables

BI = np.random.rand(num_items)
BU = np.random.rand(num_users)
Q = np.random.rand(num_features, num_items)
P = np.random.rand(num_features, num_users)

In [10]:
# Check initial variables

print('BI = ', BI)
print('-----------------------')
print('BU = ', BU)
print('-----------------------')
print('Q = ')
print(Q)
print('-----------------------')
print('P = ')
print(P)

BI =  [0.40846343 0.69520963 0.5951661  0.10236293 0.88914114]
-----------------------
BU =  [0.32025515 0.81406769 0.33442091 0.77201511 0.94980757]
-----------------------
Q = 
[[0.96830493 0.74770372 0.29836004 0.56182917 0.72984379]
 [0.70584503 0.65166008 0.59395786 0.80917178 0.90636573]]
-----------------------
P = 
[[0.73181605 0.83447084 0.86554109 0.23145469 0.67745222]
 [0.27429646 0.77825462 0.24811325 0.71064664 0.03802084]]


In [11]:
# Verify initial MAE

R_pred = m + BI[np.newaxis,:] + BU[:,np.newaxis] + P.T.dot(Q)
mae = abs(R[R>0]-R_pred[R>0]).mean()
print(mae)

1.96854892499255


In [12]:
#set learning rate
alpha = 0.1

#set number of epoch
epoch_num = 30

In [13]:
for epoch in range(epoch_num):
  for u,i in np.argwhere(R>-1):
    # predict the r^
    r_pred = m + BI[i] + BU[u] + P[:,u].T.dot(Q[:,i])

    # traning
    BI[i] = BI[i] - alpha*(r_pred-R[u,i])
    BU[u] = BU[u] - alpha*(r_pred-R[u,i])
    Q[:,i] = Q[:,i] - alpha*(r_pred-R[u,i])*P[:,u]
    P[:,u] = P[:,u] - alpha*(r_pred-R[u,i])*Q[:,i]

In [14]:
# Check trained variables

print('BI = ', BI)
print('-----------------------')
print('BU = ', BU)
print('-----------------------')
print('Q = ')
print(Q)
print('-----------------------')
print('P = ')
print(P)

BI =  [-0.15162307  0.06671002  0.00788585 -0.08197028  0.18780495]
-----------------------
BU =  [-0.23222654  1.11389325 -0.36347238  0.53955133 -0.52871497]
-----------------------
Q = 
[[-0.14004683  0.54114894 -0.89331055  0.51532389  0.9032105 ]
 [ 0.83682169 -0.92559825  0.16487982  0.74193113  1.42248143]]
-----------------------
P = 
[[-0.00953064 -0.36037875  1.22100083 -0.14226641  1.42123773]
 [-0.38941655 -0.42282335 -1.0936907   1.2473915   1.00705326]]


In [20]:
# Predicted the Rating Matrix

R_PRED = m + BI[np.newaxis,:] + BU[:,np.newaxis] + P.T.dot(Q)

print(R_PRED.round(1))

[[1.9 2.8 2.3 2.  2. ]
 [3.3 4.  4.  3.2 3. ]
 [1.  4.  1.  2.  2. ]
 [4.1 2.  3.5 3.9 5. ]
 [2.6 2.  1.  3.5 5. ]]


In [18]:
# Verify MAE after training

mae = np.abs(R[R>0]-R_PRED[R>0]).mean()
print(mae)

0.00984292905904166




---



https://rathachai.creatier.pro/